from .famaly_love_quiz import FamalyLoveQuizService, get_famaly_love_quiz
from .client import ClientService, get_client_service
from .compatibility_quiz import CompatibilityQuizService, get_compatibility_quiz_service
from .famaly_love_image import FamalyLoveImageService, get_famaly_love_image_service
from .mbti_quiz import MBTIQuizService, get_mbti_quiz_service
from .smol_quiz import SMOLQuizService, get_smol_quiz_service
