from .client import AbstractDALClient
from .compatibility_quiz import AbstractDALCompatibilityQuiz
from .famaly_love_image import AbstractDALFamalyLoveImage
from .famaly_love_quiz import AbstractDALFamalyLoveQuiz
from .mbti_quiz import AbstractDALMBTIQuiz
from .smol_quiz import AbstractDALSMOLQuiz
